import type { Incident, MemoryEntry, AnalyticsData, DashboardStats } from './types';

// ============================================================
// Realistic production incident data
// ============================================================

export const demoIncidents: Incident[] = [
  {
    id: 'INC-1038',
    title: 'Redis cache cluster failover',
    service: 'Cache Layer',
    severity: 'SEV-2',
    status: 'resolved',
    triggeredAt: '2026-09-15T03:22:00Z',
    resolvedAt: '2026-09-15T04:45:00Z',
    symptoms: [
      'Cache hit ratio dropped from 94% to 12%',
      'Elevated latency across all dependent services',
      'Redis primary node unresponsive',
    ],
    logs: [
      '[03:22:14] WARN redis-cluster: Primary node redis-prod-01 health check failed',
      '[03:22:45] ERROR redis-cluster: Connection refused on redis-prod-01:6379',
      '[03:23:01] INFO redis-cluster: Initiating automatic failover to replica redis-prod-02',
      '[03:23:18] ERROR redis-cluster: Failover failed — replica lag exceeds threshold (2.4GB)',
    ],
    errorInfo: 'Redis primary OOM killed by kernel. Replica too far behind for safe promotion.',
    rootCause: 'Memory pressure on Redis primary caused OOM kill. maxmemory-policy was set to noeviction, causing unbounded growth.',
    resolution: 'Set maxmemory-policy to allkeys-lru, increased instance memory to 16GB, restarted cluster with replica promotion.',
    resolutionOutcome: 'successful',
    lessonsLearned: 'Always configure eviction policy. Monitor memory usage with alerts at 70% and 85% thresholds.',
    memoryUsed: false,
    tags: ['redis', 'cache', 'oom', 'failover'],
  },
  {
    id: 'INC-1039',
    title: 'Authentication service token validation failures',
    service: 'Auth Service',
    severity: 'SEV-1',
    status: 'resolved',
    triggeredAt: '2026-09-16T14:05:00Z',
    resolvedAt: '2026-09-16T14:52:00Z',
    symptoms: [
      '401 Unauthorized responses spiked to 68% of all requests',
      'Users reporting inability to log in across mobile and web',
      'JWT validation errors in auth-service logs',
    ],
    logs: [
      '[14:05:22] ERROR auth-service: JWT signature verification failed — key ID "prod-key-2026-q3" not found in JWKS',
      '[14:05:23] ERROR auth-service: 847 token validation failures in last 60s',
      '[14:06:01] WARN auth-service: JWKS endpoint returning stale keyset (last-modified: 2026-09-01)',
      '[14:08:44] INFO auth-service: Key rotation detected — new key ID "prod-key-2026-q3-v2" deployed but not in JWKS cache',
    ],
    errorInfo: 'JWKS cache was stale after scheduled key rotation. TTL was 24h but rotation happened mid-cycle.',
    rootCause: 'Scheduled signing key rotation occurred but JWKS cache (24h TTL) was not invalidated, causing all new tokens to fail validation.',
    resolution: 'Flushed JWKS cache, reduced cache TTL to 5 minutes, added cache invalidation hook to key rotation pipeline.',
    resolutionOutcome: 'successful',
    lessonsLearned: 'Key rotation must trigger JWKS cache invalidation. Add integration test for rotation + validation flow.',
    memoryUsed: false,
    tags: ['auth', 'jwt', 'key-rotation', 'cache'],
  },
  {
    id: 'INC-1040',
    title: 'Payment gateway timeout surge',
    service: 'Payment Service',
    severity: 'SEV-1',
    status: 'resolved',
    triggeredAt: '2026-09-18T09:30:00Z',
    resolvedAt: '2026-09-18T10:15:00Z',
    symptoms: [
      'Payment processing latency exceeded 30s timeout',
      '34% of checkout attempts failing with gateway timeout',
      'Revenue impact estimated at $12K/minute',
    ],
    logs: [
      '[09:30:15] ERROR payment-svc: Stripe API timeout after 30000ms — POST /v1/charges',
      '[09:30:16] ERROR payment-svc: Circuit breaker OPEN for stripe-primary after 15 consecutive failures',
      '[09:31:00] WARN payment-svc: Fallback to stripe-secondary endpoint activated',
      '[09:31:02] ERROR payment-svc: stripe-secondary also timing out — possible upstream outage',
    ],
    errorInfo: 'Stripe API experiencing elevated latency globally. Status page confirmed degraded performance.',
    rootCause: 'Upstream Stripe API degradation combined with insufficient timeout/retry configuration and missing fallback payment processor.',
    resolution: 'Activated queued payment processing mode, reduced timeout to 10s with exponential backoff, enabled Adyen as fallback processor.',
    resolutionOutcome: 'successful',
    lessonsLearned: 'Implement multi-provider payment strategy. Queue payments during outages rather than failing immediately.',
    memoryUsed: false,
    tags: ['payment', 'timeout', 'stripe', 'circuit-breaker'],
  },
  {
    id: 'INC-1041',
    title: 'Kubernetes pod eviction cascade',
    service: 'Platform',
    severity: 'SEV-2',
    status: 'resolved',
    triggeredAt: '2026-09-20T22:10:00Z',
    resolvedAt: '2026-09-21T00:30:00Z',
    symptoms: [
      'Multiple pods evicted across production namespace',
      'Node memory pressure detected on 3 of 8 nodes',
      'Service degradation across checkout, search, and recommendation services',
    ],
    logs: [
      '[22:10:05] WARN kubelet: Node prod-node-04 memory pressure — evicting pods',
      '[22:10:12] INFO kubelet: Evicted pod checkout-api-7d8f9c-x4k2q (BestEffort QoS)',
      '[22:10:18] INFO kubelet: Evicted pod search-svc-5b6c7d-m3n1p (Burstable QoS, exceeded limit)',
      '[22:15:33] WARN cluster-autoscaler: Unable to scale up — max node count (8) reached',
    ],
    errorInfo: 'Memory leak in search service caused node-level memory pressure, triggering cascading pod evictions.',
    rootCause: 'Search service memory leak (unbounded query result caching) caused node memory pressure. Pod resource limits were too permissive.',
    resolution: 'Fixed search service cache with bounded LRU, set proper resource requests/limits, increased max node count to 12.',
    resolutionOutcome: 'successful',
    lessonsLearned: 'All pods must have Guaranteed or properly configured Burstable QoS. Implement pod disruption budgets.',
    memoryUsed: false,
    tags: ['kubernetes', 'pod-eviction', 'memory-leak', 'resource-limits'],
  },
  {
    id: 'INC-1042',
    title: 'Checkout API latency spike',
    service: 'Checkout API',
    severity: 'SEV-2',
    status: 'resolved',
    triggeredAt: '2026-09-22T10:15:00Z',
    resolvedAt: '2026-09-22T11:20:00Z',
    symptoms: [
      'p95 latency increased from 320ms to 4.8s',
      'Database connection pool utilization at 100%',
      'Timeout errors in checkout flow',
      'Active database connections: 200/200 (maxed)',
    ],
    logs: [
      '[10:15:33] WARN checkout-api: Connection pool exhausted — 200/200 active connections',
      '[10:15:34] ERROR checkout-api: Unable to acquire connection within 5000ms timeout',
      '[10:16:01] ERROR checkout-api: PgPool: timeout waiting for available connection',
      '[10:16:45] WARN checkout-api: Request queue depth: 847 pending requests',
    ],
    errorInfo: 'PostgreSQL connection pool exhaustion causing cascading timeouts in checkout flow.',
    rootCause: 'Database connection pool exhaustion caused by a long-running analytical query holding connections and a recent traffic spike from a marketing campaign.',
    resolution: 'Killed long-running query, increased connection pool size from 200 to 350, added connection timeout of 3s, implemented query timeout of 10s.',
    resolutionOutcome: 'successful',
    lessonsLearned: 'Separate OLTP and OLAP workloads. Set statement_timeout on production database. Monitor connection pool utilization with alerts at 70%.',
    memoryUsed: false,
    tags: ['database', 'connection-pool', 'latency', 'postgresql'],
  },
  {
    id: 'INC-1043',
    title: 'CDN origin shield saturation',
    service: 'CDN / Edge',
    severity: 'SEV-3',
    status: 'resolved',
    triggeredAt: '2026-09-23T16:00:00Z',
    resolvedAt: '2026-09-23T17:30:00Z',
    symptoms: [
      'Static asset load times increased 5x globally',
      'Origin server CPU at 98%',
      'CDN cache hit ratio dropped from 96% to 23%',
    ],
    logs: [
      '[16:00:22] WARN cdn-edge: Cache MISS rate exceeding threshold (77%)',
      '[16:01:15] ERROR origin-server: Request rate exceeded capacity — 12,000 req/s vs 3,000 req/s baseline',
      '[16:02:00] WARN cdn-edge: Origin shield returning 503 for 34% of requests',
    ],
    errorInfo: 'Cache purge accidentally cleared entire CDN edge cache, causing thundering herd on origin.',
    rootCause: 'Full CDN cache purge instead of targeted purge caused thundering herd effect on origin servers.',
    resolution: 'Implemented request coalescing at origin shield, added stale-while-revalidate headers, created purge safeguards.',
    resolutionOutcome: 'successful',
    lessonsLearned: 'Never allow full cache purge in production without approval. Implement stale-while-revalidate as default.',
    memoryUsed: false,
    tags: ['cdn', 'cache', 'thundering-herd', 'origin'],
  },
  {
    id: 'INC-1044',
    title: 'Order processing queue backlog',
    service: 'Order Service',
    severity: 'SEV-2',
    status: 'resolved',
    triggeredAt: '2026-09-24T11:00:00Z',
    resolvedAt: '2026-09-24T12:45:00Z',
    symptoms: [
      'Order processing delayed by 15+ minutes',
      'Message queue depth: 45,000 (normal: <500)',
      'Consumer lag increasing steadily',
    ],
    logs: [
      '[11:00:30] WARN order-consumer: Consumer lag exceeding 30,000 messages',
      '[11:01:00] ERROR order-consumer: Processing rate: 50 msg/s (normal: 2,000 msg/s)',
      '[11:02:15] WARN order-consumer: Serialization errors on 12% of messages — schema mismatch',
    ],
    errorInfo: 'Schema change in order events broke deserialization for 12% of messages, causing consumer slowdown.',
    rootCause: 'Backward-incompatible schema change in order events deployed without consumer update. Dead letter queue not configured.',
    resolution: 'Rolled back schema change, deployed compatible consumer version, configured DLQ, replayed failed messages.',
    resolutionOutcome: 'successful',
    lessonsLearned: 'Enforce schema compatibility checks in CI. Always configure DLQ for message queues. Deploy consumers before producers for breaking changes.',
    memoryUsed: false,
    tags: ['queue', 'kafka', 'schema', 'consumer-lag'],
  },
  {
    id: 'INC-1045',
    title: 'API gateway rate limiter malfunction',
    service: 'API Gateway',
    severity: 'SEV-2',
    status: 'resolved',
    triggeredAt: '2026-09-25T08:30:00Z',
    resolvedAt: '2026-09-25T09:15:00Z',
    symptoms: [
      'Legitimate API requests being rate-limited (429 responses)',
      'Partner integrations reporting access denied',
      'Rate limit counter not resetting between windows',
    ],
    logs: [
      '[08:30:12] WARN api-gateway: Rate limit exceeded for client partner-acme — 0/1000 remaining',
      '[08:30:13] ERROR api-gateway: Redis EVAL error — rate limiter script timeout',
      '[08:31:00] WARN api-gateway: Falling back to in-memory rate limiter (incorrect counts)',
    ],
    errorInfo: 'Redis-backed rate limiter script timed out, fallback in-memory limiter had stale counters from previous window.',
    rootCause: 'Redis slowlog showed rate limiter Lua script blocked by a key migration operation. In-memory fallback did not reset window counters.',
    resolution: 'Fixed in-memory fallback counter reset logic, added rate limiter script timeout handling, separated rate limiter Redis from application Redis.',
    resolutionOutcome: 'successful',
    lessonsLearned: 'Rate limiter infrastructure must be isolated. Fallback limiters need proper window reset. Test failover path regularly.',
    memoryUsed: false,
    tags: ['api-gateway', 'rate-limiting', 'redis', 'fallback'],
  },
  // These two are for the DEMO — incident 1 resolved, incident 2 will recall it
  {
    id: 'INC-1046',
    title: 'Inventory service database connection exhaustion',
    service: 'Inventory Service',
    severity: 'SEV-2',
    status: 'resolved',
    triggeredAt: '2026-09-26T13:00:00Z',
    resolvedAt: '2026-09-26T14:10:00Z',
    symptoms: [
      'Inventory lookups timing out',
      'Database connection pool at 100% capacity',
      'p99 latency: 8.2s (baseline: 180ms)',
      'Active connections: 150/150',
    ],
    logs: [
      '[13:00:15] WARN inventory-svc: Connection pool exhausted — 150/150 active',
      '[13:00:16] ERROR inventory-svc: Cannot acquire connection — pool timeout after 5000ms',
      '[13:01:00] ERROR inventory-svc: 23 queries running > 30s — possible lock contention',
      '[13:02:30] WARN inventory-svc: Deadlock detected between transactions on products table',
    ],
    errorInfo: 'Connection pool exhaustion due to lock contention from concurrent bulk inventory updates.',
    rootCause: 'Bulk inventory update job running during peak hours caused lock contention, exhausting the connection pool. No connection timeout configured.',
    resolution: 'Rescheduled bulk updates to off-peak window, added row-level locking with SKIP LOCKED, increased pool to 200 with 3s acquisition timeout.',
    resolutionOutcome: 'successful',
    lessonsLearned: 'Schedule bulk operations during off-peak hours. Use SKIP LOCKED for concurrent batch processing. Always set connection acquisition timeouts.',
    memoryUsed: false,
    tags: ['database', 'connection-pool', 'lock-contention', 'postgresql'],
  },
  {
    id: 'INC-1047',
    title: 'Search service memory leak — recurring',
    service: 'Search Service',
    severity: 'SEV-3',
    status: 'investigating',
    triggeredAt: '2026-09-27T19:45:00Z',
    symptoms: [
      'Heap usage growing linearly — 4.2GB and rising',
      'GC pause times increasing (200ms → 1.2s)',
      'Search response times degrading progressively',
    ],
    logs: [
      '[19:45:10] WARN search-svc: Heap usage 4.2GB / 6GB (70%) — trending upward',
      '[19:46:00] WARN search-svc: GC pause 1.2s — exceeds 500ms threshold',
      '[19:47:30] WARN search-svc: Response time p95: 2.1s (baseline: 350ms)',
    ],
    errorInfo: 'Memory leak suspected in search query result caching layer.',
    memoryUsed: true,
    memoryIds: ['mem-1041'],
    tags: ['memory-leak', 'search', 'heap', 'gc'],
  },
];

// ============================================================
// Pre-stored memories (from past resolved incidents)
// ============================================================

export const demoMemories: MemoryEntry[] = [
  {
    id: 'mem-1038',
    incidentId: 'INC-1038',
    title: 'Redis cache cluster failover',
    service: 'Cache Layer',
    severity: 'SEV-2',
    symptoms: ['Cache hit ratio drop', 'Primary node unresponsive', 'Elevated latency'],
    rootCause: 'Redis primary OOM killed. maxmemory-policy set to noeviction causing unbounded growth.',
    attemptedActions: ['Automatic failover to replica', 'Manual restart of primary'],
    successfulActions: ['Set maxmemory-policy to allkeys-lru', 'Increased instance memory', 'Restarted with replica promotion'],
    failedActions: ['Automatic failover failed due to replica lag'],
    resolution: 'Configured eviction policy, increased memory, promoted replica after sync.',
    outcome: 'successful',
    lessonsLearned: 'Always configure eviction policy. Monitor memory with alerts at 70% and 85%.',
    timestamp: '2026-09-15T04:45:00Z',
    tags: ['redis', 'cache', 'oom', 'failover'],
  },
  {
    id: 'mem-1042',
    incidentId: 'INC-1042',
    title: 'Checkout API latency spike — connection pool exhaustion',
    service: 'Checkout API',
    severity: 'SEV-2',
    symptoms: ['p95 latency spike to 4.8s', 'Connection pool at 100%', 'Timeout errors', 'Pending request queue buildup'],
    rootCause: 'Database connection pool exhaustion from long-running analytical query combined with traffic spike.',
    attemptedActions: ['Identified long-running queries', 'Scaled horizontally'],
    successfulActions: ['Killed long-running query', 'Increased pool size 200→350', 'Added connection timeout 3s', 'Set query timeout 10s'],
    failedActions: ['Horizontal scaling alone did not help — pool was the bottleneck'],
    resolution: 'Killed blocking query, increased pool size, added timeouts at connection and query level.',
    outcome: 'successful',
    lessonsLearned: 'Separate OLTP and OLAP workloads. Set statement_timeout. Alert on pool utilization at 70%.',
    timestamp: '2026-09-22T11:20:00Z',
    tags: ['database', 'connection-pool', 'latency', 'postgresql'],
  },
  {
    id: 'mem-1046',
    incidentId: 'INC-1046',
    title: 'Inventory service database connection exhaustion',
    service: 'Inventory Service',
    severity: 'SEV-2',
    symptoms: ['Connection pool at 100%', 'Lookups timing out', 'p99 latency spike', 'Lock contention / deadlocks'],
    rootCause: 'Bulk inventory update during peak hours caused lock contention, exhausting connection pool.',
    attemptedActions: ['Investigated slow queries', 'Checked for deadlocks'],
    successfulActions: ['Rescheduled bulk updates to off-peak', 'Added SKIP LOCKED', 'Increased pool with acquisition timeout'],
    failedActions: ['Simply increasing pool without fixing locks did not resolve the issue'],
    resolution: 'Rescheduled bulk ops, used SKIP LOCKED for concurrent processing, added acquisition timeout.',
    outcome: 'successful',
    lessonsLearned: 'Schedule bulk operations off-peak. Use SKIP LOCKED for batch processing. Set connection acquisition timeouts.',
    timestamp: '2026-09-26T14:10:00Z',
    tags: ['database', 'connection-pool', 'lock-contention', 'postgresql'],
  },
  {
    id: 'mem-1041',
    incidentId: 'INC-1041',
    title: 'Kubernetes pod eviction cascade from memory leak',
    service: 'Platform',
    severity: 'SEV-2',
    symptoms: ['Pod evictions', 'Node memory pressure', 'Service degradation'],
    rootCause: 'Search service memory leak (unbounded query result caching) caused node memory pressure and cascading evictions.',
    attemptedActions: ['Investigated node memory usage', 'Identified leaking pods'],
    successfulActions: ['Fixed cache with bounded LRU', 'Set resource requests/limits', 'Increased max nodes'],
    failedActions: ['Restarting pods was temporary — leak recurred within hours'],
    resolution: 'Bounded the search service cache, set proper resource limits, expanded cluster capacity.',
    outcome: 'successful',
    lessonsLearned: 'All pods must have proper QoS class. Implement pod disruption budgets. Bound all in-memory caches.',
    timestamp: '2026-09-21T00:30:00Z',
    tags: ['kubernetes', 'memory-leak', 'pod-eviction', 'resource-limits'],
  },
];

// ============================================================
// Dashboard stats
// ============================================================

export const demoDashboardStats: DashboardStats = {
  activeIncidents: 2,
  criticalIncidents: 0,
  resolvedIncidents: 8,
  avgResolutionMinutes: 72,
  aiAssistedResolutions: 6,
  memoryAssistedInvestigations: 3,
  totalMemories: 4,
  successfulResolutions: 7,
  lessonsLearned: 8,
  recurringPatterns: 3,
};

// ============================================================
// Analytics data
// ============================================================

export const demoAnalytics: AnalyticsData = {
  incidentsOverTime: [
    { date: '2026-09-15', count: 1 },
    { date: '2026-09-16', count: 1 },
    { date: '2026-09-17', count: 0 },
    { date: '2026-09-18', count: 1 },
    { date: '2026-09-19', count: 0 },
    { date: '2026-09-20', count: 1 },
    { date: '2026-09-21', count: 0 },
    { date: '2026-09-22', count: 1 },
    { date: '2026-09-23', count: 1 },
    { date: '2026-09-24', count: 1 },
    { date: '2026-09-25', count: 1 },
    { date: '2026-09-26', count: 1 },
    { date: '2026-09-27', count: 1 },
  ],
  severityDistribution: [
    { severity: 'SEV-1', count: 2 },
    { severity: 'SEV-2', count: 6 },
    { severity: 'SEV-3', count: 2 },
    { severity: 'SEV-4', count: 0 },
  ],
  topServices: [
    { service: 'Checkout API', count: 2 },
    { service: 'Payment Service', count: 1 },
    { service: 'Auth Service', count: 1 },
    { service: 'Cache Layer', count: 1 },
    { service: 'Platform', count: 1 },
    { service: 'Search Service', count: 1 },
    { service: 'Inventory Service', count: 1 },
  ],
  topRootCauses: [
    { cause: 'Connection pool exhaustion', count: 3 },
    { cause: 'Memory leak / OOM', count: 2 },
    { cause: 'Cache invalidation failure', count: 2 },
    { cause: 'Upstream service degradation', count: 1 },
    { cause: 'Schema incompatibility', count: 1 },
  ],
  resolutionTimeTrend: [
    { date: '2026-09-15', avgMinutes: 83 },
    { date: '2026-09-16', avgMinutes: 47 },
    { date: '2026-09-18', avgMinutes: 45 },
    { date: '2026-09-20', avgMinutes: 140 },
    { date: '2026-09-22', avgMinutes: 65 },
    { date: '2026-09-23', avgMinutes: 90 },
    { date: '2026-09-24', avgMinutes: 105 },
    { date: '2026-09-25', avgMinutes: 45 },
    { date: '2026-09-26', avgMinutes: 70 },
  ],
  memoryUsageTrend: [
    { date: '2026-09-15', recalls: 0, retains: 1 },
    { date: '2026-09-16', recalls: 0, retains: 1 },
    { date: '2026-09-18', recalls: 0, retains: 1 },
    { date: '2026-09-20', recalls: 0, retains: 1 },
    { date: '2026-09-22', recalls: 1, retains: 1 },
    { date: '2026-09-24', recalls: 1, retains: 1 },
    { date: '2026-09-26', recalls: 2, retains: 1 },
    { date: '2026-09-27', recalls: 1, retains: 0 },
  ],
};
